### ISSUE TITLE
Code for multiple tasks in the project page

### ISSUE THREAD

**Issue by zchoi** [UMass-Foundation-Model/3D-LLM#12]
Thanks for the insightful work！Will the training code for the tasks mentioned on the project page be released? I am interested in the research regarding EQA and navigation～😊.

**Comment by evelinehong** [comment]
Thanks for asking! 3D-LLM is a general model that unifies the inputs / outputs of all tasks. Thus the code released can be used for all tasks.

We will release the model soon.
