### ISSUE TITLE
Training batch size

### ISSUE THREAD

**Issue by ZichengDuan** [UMass-Foundation-Model/3D-LLM#15]
Hi, thanks for sharing your fantastic work! As indicated in the paper, when using BLIP-2 as backbones, it requires 64 V100s to train the model with batch size 128 on 8 nodes (16 per node), while using Flamingo, it requires 8 A100, with batch size 16. I wonder if it's possible to train with a smaller batch size? Many thanks.

**Comment by evelinehong** [comment]
Yes. We also tried using batch size 1/4/8, on single debug gpu and it works fine.
