### ISSUE TITLE
How to align scene_ids in `data_part2_scene.json` from those in ScanNet?

### ISSUE THREAD

**Issue by ch3cook-fdu** [UMass-Foundation-Model/3D-LLM#23]
I notice that the scene_ids in `data_part2_scene.json` have a dtype of `int`, while the scene_ids in scannet are something like `scene0000_00`. So, how do I align these two datasets? Or how can I split the scannet annotations from that file by myself?

**Comment by evelinehong** [comment]
please refer to https://drive.google.com/drive/folders/1bJpK00UFRZGH7tdx3PaqDrrTfHNP6B2K?usp=drive_link

**Comment by cy94** [comment]
Hello,
I used the `final_scene_map_dict_scan_v2.json` file but it doesnt contain scene ID mappings for all the annotations in `data_part2_scene_v2.json`. Is there are a different scene ID mapping that I can use?

**Comment by ch3cook-fdu** [comment]
There will be roughly ~23k annotations after dropping duplicates, and with:

1) 1,033 descriptions on 517 scenes,
2) 1,864 lines of embodied task planning on 510 scenes,
3) 2,955 lines of multi-turn embodied dialogues on 517 scenes.

The rest of the annotations are 3D question answer pairs.

**Comment by cy94** [comment]
I found 60582 in data_part2_scene_v2.json, is that the right file to use?

**Comment by ch3cook-fdu** [comment]
I am using the following code for filtering:

```{python}
import json
mapping_file = json.load(open('final_scene_map_dict_scan_v2.json', 'r'))
data = json.load(open('data_part2_scene.json', 'r'))
scannet_annotations = []
corpus = set()
for anno in data:
    scannet_scene_id = mapping_file.get(str(anno['scene_id']), None)
    if scannet_scene_id is None:
        continue
    scannet_annotations.append(anno)
print(len(scannet_annotations))
```

**Comment by cy94** [comment]
I see, I'm using data_part2_scene_v2.json, I didn't see v1 (data_part2_scene.json) anywhere on your Google Drive. Maybe thats why there are more?
