### ISSUE TITLE
What is `objaverse_frame_cap3d`?

### ISSUE THREAD

**Issue by hrtang** [UMass-Foundation-Model/3D-LLM#24]
I was following [gen_features](https://github.com/UMass-Foundation-Model/3D-LLM/tree/main/3DLanguage_data/ChatCaptioner_based/gen_features) in **Step3: 3D feature construction from rendered images**, but ran into a blocker.

Apparently `sam_mask.py` expects `objaverse_frame_cap3d` to contain different image views of a "room". Where/how are those images generated?

Your help would be greatly appreciated!

**Comment by anyeZHY** [comment]
Your question about these image views can be generated using `3DLanguage_data/ChatCaptioner_based/objaverse_render`. You need to link the rendered output directory to the corresponding directory, as shown in https://github.com/UMass-Foundation-Model/3D-LLM/tree/main/3DLanguage_data/ChatCaptioner_based/gen_features#preparation.

**Comment by hrtang** [comment]
Makes sense. But the output files of `objaverse_render/render.py` are `rgb_outside_*.png` https://github.com/UMass-Foundation-Model/3D-LLM/blob/770b2a19330883be3baf207ed68b359658a0d5d6/3DLanguage_data/ChatCaptioner_based/objaverse_render/render.py#L86
and `sam_mask.py` is expecting `*view*png`
https://github.com/UMass-Foundation-Model/3D-LLM/blob/770b2a19330883be3baf207ed68b359658a0d5d6/3DLanguage_data/ChatCaptioner_based/gen_features/sam_mask.py#L105

Maybe the output format should change somehow?

**Comment by evelinehong** [comment]
fixed in https://github.com/UMass-Foundation-Model/3D-LLM/commit/cf5f5f65e03762aba60fae550bb14fc59fec3f02
