### ISSUE TITLE
Some questions about the code

### ISSUE THREAD

**Issue by xbq1994** [UMass-Foundation-Model/3D-LLM#28]
Hi, I have some questions:
1. As there are no descriptions about "task_type" in the annotations, how to split the 'data_part1_all_objaverse.json' and 'data_part2_scene.json' into train/val/test sets in proportion of (8:1:1)?
2.  I found you have uploaded files "voxelized_features_sam_nonzero_preprocess.zip" and "voxelized_voxels_sam_nonzero_preprocess.zip", what's that for?
3. During the evaluation, the code needs the "coco_fmt_qust_file" annotations for computing accuracy. However there are no descriptions about "coco_fmt_qust_file" in the annotations, so how to calculate the test accuracy?

>                 if hasattr(dataset[split], "coco_fmt_qust_file") and dataset[split].coco_fmt_qust_file is not None:
>                     self.ques_files[split] = dataset[split].coco_fmt_qust_file
>                     self.anno_files[split] = dataset[split].coco_fmt_anno_file

**Comment by evelinehong** [comment]
1. evaluation set: https://drive.google.com/drive/folders/1tdvEW5iB-ZEPo1tCqEAqKKhgHiDd4Dx0?usp=drive_link
2. scannet features and point clouds 
3. we do not need that in the evaluation. We have uploaded our own evaluation scripts
