### ISSUE TITLE
For the json files used in pretraining, did you split them to train, val and test?

### ISSUE THREAD

**Issue by jiuyouyun9** [UMass-Foundation-Model/3D-LLM#37]
For the json files used in pretraining, like 'data_part2_scene_v2.json', 'data_part1_all_objaverse.json', did you use them all for training? Or used some part of them for val and test? If so, which parts are for val and test?

**Comment by evelinehong** [comment]
see https://drive.google.com/drive/folders/1tdvEW5iB-ZEPo1tCqEAqKKhgHiDd4Dx0?usp=drive_link for val set
