### ISSUE TITLE
the processing of objaverse feature 

### ISSUE THREAD

**Issue by SwimZhang** [UMass-Foundation-Model/3D-LLM#41]
Hi

When I run the blip_oa.py in '3DLanguage_data/ChatCaptioner_based/gen_features/'
The Error: RuntimeError: Input type (unsigned char) and bias type (c10::Half) should be the same.
I try to revise the code: 'output = visual_encoder(image.float())' in 167.  Is it OK? 

Another one, It seems the number of rendered images should be 8, not 4
![image](https://github.com/UMass-Foundation-Model/3D-LLM/assets/29268707/f83de4f8-07b9-4db7-96f5-a090b5d87df3)

**Comment by anyeZHY** [comment]
> When I run the blip_oa.py in '3DLanguage_data/ChatCaptioner_based/gen_features/'
The Error: RuntimeError: Input type (unsigned char) and bias type (c10::Half) should be the same.
I try to revise the code: 'output = visual_encoder(image.float())' in 167. Is it OK?

For the first question, we have already update the script for generating features. #43

> Another one, It seems the number of rendered images should be 8, not 4

In our final version, we use 4 images to generate the caption using ChatCaptioner. This produces the best results. However, you can choose any number of viewpoints when generating features. You can modify the theta view in this line:

https://github.com/UMass-Foundation-Model/3D-LLM/blob/9717617bc7e68ad0e5a571c58774e7db64c042f9/3DLanguage_data/ChatCaptioner_based/objaverse_render/render.py#L52-L63

**Comment by SwimZhang** [comment]
![image](https://github.com/UMass-Foundation-Model/3D-LLM/assets/29268707/3ac092e4-4132-4b55-abcc-755cdb09b194)

As shown in the annotated part , the program cannot be executed if < 25 or 8.

Did you use 4 images or 8 images to render the open source object data you previously used？

**Comment by anyeZHY** [comment]
When generating the 3D features, we used 8 images.
