### ISSUE TITLE
How to process scannet dataset?

### ISSUE THREAD

**Issue by SwimZhang** [UMass-Foundation-Model/3D-LLM#44]
I have downloaded the scannet dataset from  https://kaldir.vc.in.tum.de/scannet_benchmark/documentation. (scannet_frames_25k). When I run python direct_3d.py in three steps for scene, it looks like a lot of json files are missing, such as,
![1697773800487](https://github.com/UMass-Foundation-Model/3D-LLM/assets/29268707/e9c8094f-785a-4d1f-a2a4-aa515e72ed36)

How to render the  original scannet dataset?  Could you have your own script ? 

Thanks very much.

**Comment by evelinehong** [comment]
For scannet, you could neglect the room bboxes.

Scannet also provides depths and poses, which could be loaded here.
You could use this one https://github.com/ScanNet/ScanNet#scannet-c-toolkit to extract more images / depths / poses.

Alternatively, you could use our released features https://drive.google.com/drive/folders/188Yd7tmiUfyct-dVMpkQ8q_tnqkb-4bo?usp=drive_link

**Comment by YunzeMan** [comment]
@SwimZhang May I ask how you get scannet 3D projection working? I run into the same problem of missing depth.npy, pose.json, and room_bbox_xxx.json files. And there seems no explanation about how these data should be prepared.
