### ISSUE TITLE
How to evaluate?

### ISSUE THREAD

**Issue by ch3cook-fdu** [UMass-Foundation-Model/3D-LLM#47]
I could not find released version of validation set for 3D Captioning, 3D-assisted Dialog, Task Decomposition, how could we evaluate the model's performance for these tasks in figure 3?

**Comment by evelinehong** [comment]
Hi! There will be further commits after CVPR deadline

**Comment by ustcwhy** [comment]
> Hi! There will be further commits after CVPR deadline

Hello, thanks for your wonderful work. Any updates now?

**Comment by zhangsha1024** [comment]
> Hi! There will be further commits after CVPR deadline

Hello. Great Work! Are there any plans for future releases or updates to the evaluation set?

**Comment by evelinehong** [comment]
find in https://drive.google.com/drive/folders/1tdvEW5iB-ZEPo1tCqEAqKKhgHiDd4Dx0?usp=drive_link
