### ISSUE TITLE
How to ensure the accuracy of the data 

### ISSUE THREAD

**Issue by ChirsHuanhuan** [UMass-Foundation-Model/3D-LLM#49]
Hello, thank you for doing such an inspiring job.
I would like to ask a question, how do you ensure the accuracy of this data when performing 3D-Language Data Generation? Or is there a detection mechanism to detect it?
Hope to receive an answer, thank you!
You guys are really great, I’m so envious!
In Chinese, niubi!

**Comment by evelinehong** [comment]
In 3D-LLM, like LLAVA we do not check the quality of the generated GPT-generated data.
However, our new paper https://vis-www.cs.umass.edu/multiply/ suggests that we could place an agent in the embodied environment to execute the tasks for ensuring quality.
An alternative way is to use hallucination scores to examine the quality https://arxiv.org/pdf/2305.10355.pdf
