### ISSUE TITLE
Can you share the script of prompting ChatGPT to generate the description of 3D data?

### ISSUE THREAD

**Issue by xianzhengma** [UMass-Foundation-Model/3D-LLM#53]
Nice work!

I want to see how accurate the ChatGPT can generate based on different 3D scenes. 

Could you push the related scripts to this github, which may be very helpful.

Xianzheng

**Comment by evelinehong** [comment]
https://github.com/UMass-Foundation-Model/3D-LLM/tree/main/3DLanguage_data/main_gpt

**Comment by xianzhengma** [comment]
Thanks a lot !
