### ISSUE TITLE
Difference between scannet features for finetuning and for pretraining?

### ISSUE THREAD

**Issue by YunzeMan** [UMass-Foundation-Model/3D-LLM#58]
I downloaded two different pre-computed features for scannet:
- One is inside `voxelized_features_sam_nonzero_preprocess`, according to the documents, is for ScanQA finetuning
- The other part is inside `3dllm_final_scene_data_v2/features`, according to the documents, is for pretraining

The two folders have overlapping features for scannet scenes, and they are different inside. I wonder what is the difference and is there a better one to use?

**Comment by evelinehong** [comment]
you could use https://drive.google.com/drive/folders/1H1SKZsK_XpMkXntwhY4BqSxsGCRP8cgp?usp=drive_link

**Comment by evelinehong** [comment]
we'll reorganize the drive

**Comment by evelinehong** [comment]
they are basically different in terms of the scenes covered

**Comment by YunzeMan** [comment]
> they are basically different in terms of the scenes covered

Thanks for your reply but I still have some confusion. I'll give you an example:

According to the v2 mapping file, `"1008": "scene0335_00"` -- they correspond to each other. However, two files have different size and contents:
1. `scannet_features/voxelized_features_sam_nonzero_preprocess/scene0335_00.pt` is a 100M file. More specifically, `104097018` according to `ls -l`
2. `3dllm_final_scene_data_v2/features/1008.pt` is a 75M file, or `78579247` according to `ls -l`.

Since these two files should be the same scene, I'm confused by the difference here. Are they generated using different 3D encoding mechanism? If so, what's the difference?
