### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by rongmq8802** [UMass-Foundation-Model/3D-LLM#9]
When will the dataset be released? Do you have any plan to release the code that constructs the dataset?

**Comment by evelinehong** [comment]
Data construction code will be released soon (hopefully this week). Full dataset will take some while as it's too large. We'll release a subset first. 3D Feature construction code has already been released.

**Comment by ch3cook-fdu** [comment]
Thanks for the excellent work! Is there any news about the dataset?

**Comment by evelinehong** [comment]
Please refer to the Data part of README

**Comment by evelinehong** [comment]
> Thanks for the excellent work! Is there any news about the dataset?

Please refer to the Data part of README
